# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='found_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='found',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archeology.Finding', verbose_name='found by'),
        ),
    ]
