# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeology', '0002_auto_20160212_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
