# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeology', '0004_auto_20160213_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artifacts/', verbose_name='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archeology.Artifact'),
        ),
    ]
