# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeology', '0005_auto_20160213_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='found',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archeology.Finding', verbose_name='found'),
        ),
    ]
