# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeology', '0005_auto_20160213_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='discoverers',
            field=models.ManyToManyField(null=True, related_name='findings', to='people.Discoverer'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='place',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
