# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeology', '0006_auto_20160213_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='discoverers',
            field=models.ManyToManyField(blank=True, related_name='findings', to='people.Discoverer'),
        ),
    ]
